### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by Arusekk** [monsterkodi/kiki#2]
Steps to reproduce:
1. do a clean git clone
2. make sure you have no special ssh keys active for GitHub
3. run `npm install`
    - `npm install` tries to access supposedly private repo with `git ls-remote ssh://git@github.com/monsterkodi/source-map.git`

Solution I found:
Upgrade konrad and kxk dependencies to the latest versions. Works, and it is a great game BTW!

**Comment by monsterkodi** [comment]
thanks for the bug report,
glad you like the game.

**Comment by monsterkodi** [comment]
I have updated the dependencies.
Thanks again for your input.
